#ifndef __CPP_PARSER_JSON_TABLE_HXX__
# define __CPP_PARSER_JSON_TABLE_HXX__

// Generated by grammar-converter


# include <yuni/yuni.h>


namespace Grammar
{
namespace Private
{
namespace JSON
{


	struct GrammarInfos
	{
		//! Initial DFA state
		const uint initialDFAState;
		//! Initial LALR state
		const uint initialLALRState;

		//! Symbols
		const struct {
			const uint count;
			const Symbols::Entry* table;
		} symbols;
		//! Charsets
		const struct {
			const uint count;
			const Charset::Entry* table;
		} charsets;
		//! Productions
		const struct {
			const uint count;
			const Productions::Entry* table;
		} productions;
		//! DFA states
		const struct {
			const uint count;
			const DFA::Entry* table;
		} dfa;
		//! LALR states
		const struct {
			const uint count;
			const LALR::Entry* table;
		} lalr;
	};


	static const GrammarInfos grammar = 
	{
		// initial states
		   0, // initial DFA state
		   0, // initial LALR state

		// symbols
		{
			Symbols::count,
			Symbols::table,
		},
		// charsets
		{
			Charset::count,
			Charset::table,
		},
		// productions
		{
			Productions::count,
			Productions::table,
		},
		// dfa
		{
			DFA::count,
			DFA::table,
		},
		// lalr
		{
			LALR::count,
			LALR::table,
		},
	};





} // namespace JSON
} // namespace Private
} // namespace Grammar

#endif // __CPP_PARSER_JSON_TABLE_HXX__
