set(YUNI_ERROR_HAS_OCCURED   false)


macro(ynmessage)
	set(options BOLD MODULE)
	set(oneValueArgs TITLE)
	set(multiValueArgs)
	cmake_parse_arguments(opts "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
	if (UNIX)
		if (${opts_BOLD})
			message(STATUS "[1;30m{yuni}[0m  [1;37m[1m${opts_UNPARSED_ARGUMENTS}[0m")
		elseif (${opts_MODULE})
			ynmessage(TITLE "[module] " "${opts_UNPARSED_ARGUMENTS}")
		elseif (NOT "${opts_TITLE}" STREQUAL "")
			message(STATUS "[1;30m{yuni}[0m  [1;32m${opts_TITLE}[0m[1;37m[1m${opts_UNPARSED_ARGUMENTS}[0m")
		else()
			message(STATUS "[1;30m{yuni}[0m  ${opts_UNPARSED_ARGUMENTS}")
		endif()
	else()
		message(STATUS "{yuni}  ${opts_TITLE}${opts_UNPARSED_ARGUMENTS}")
	endif()
endmacro()


macro(ynwarning msg)
	if(UNIX)
		message(STATUS "[1;33m{yuni}  [warning][0m ${msg}")
	else()
		message(STATUS "{yuni}  [WARNING] ${msg}")
	endif()
endmacro()


macro(ynerror msg)
	if(UNIX)
		message(STATUS "[1;31m{yuni}  [error][0m ${msg}")
	else()
		message(STATUS "{yuni}  [ERROR] ${msg}")
	endif()
	set(YUNI_ERROR_HAS_OCCURED  true)
endmacro()


macro(ynfatal msg)
	if(UNIX)
		message(FATAL_ERROR "[1;31m{yuni}  [error][0m ${msg}")
	else()
		message(FATAL_ERROR "{yuni}  [ERROR] ${msg}")
	endif()

	set(YUNI_ERROR_HAS_OCCURED  true)
endmacro()
